### PR TITLE
Added Vue definition for the browser's window object, which resolves #9

### LINKED ISSUE #9: Wiki tutorial fix for Vue ReferenceError
Hi,

Thank you for the detailed tutorial! 
I wanted to PR a tiny fix but it seems it's a bit complicated for Wiki pages, so I just wanted to let you know I got a ReferenceError for Vue that was fixed by adding `window.Vue = Vue;` in `index.js`.

So `index.js` now looks like this:
```
window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

import Vue from 'vue';
import Demo from "./components/Demo.vue";

window.Vue = Vue;
const app = new Vue({
    el: '#app',
    components: {
        Demo
    }
});
```

Hope this helps and thank you again,
Zvi

### PR DESCRIPTION
**Pull request by ZviBaratz**
…michaelbukachi/django-vuejs-tutorial#9

Fixes a ReferenceError ('Vue' undefined) in the browser for rendered pages.

### CODE REVIEW

**Comment by ZviBaratz** [comment]
I just realized I pushed to master - let me know if you want the vuetify configuration or not and I'll revert if necessary.

**Comment by michaelbukachi** [comment]
Awesome. I've reviewed you PR and it seems okay. Though I think vuetify should be removed to keep the tutorial simple. If you can revert that and push I can merge your changes :smiley:.

**Comment by ZviBaratz** [comment]
Great, just one last question - I was getting a warning from webpack regarding "mode" definition (must be set to "development" or "production"), would you like for me to include the added `mode: 'development'` line in _webpack.config.js_ or not?

**Comment by michaelbukachi** [comment]
Yeah, sure. Setting `development` should be fine since it's just a tutorial.

**Pull request merged**
